### PR TITLE
fix(build): remove stub scanner and regenerate bindings

### LINKED ISSUE #9: Scanner is missing required functions
To reproduce, use the latest `tree-sitter` CLI and do `tree-sitter build`. Resulting error:
```
thread 'main' panicked at cli/src/main.rs:497:22:
called `Result::unwrap()` on an `Err` value: Missing required functions in the external scanner, parsing won't work without these!

  `_tree_sitter_groovy_external_scanner_create`
  `_tree_sitter_groovy_external_scanner_destroy`
  `_tree_sitter_groovy_external_scanner_serialize`
  `_tree_sitter_groovy_external_scanner_deserialize`
  `_tree_sitter_groovy_external_scanner_scan`

You can read more about this at https://tree-sitter.github.io/tree-sitter/creating-parsers#external-scanners
```

Also, please consider adding `grammar.json` to the repo, which can be used to generate the parser without requiring node.

### PR DESCRIPTION
**Pull request by clason**
- **fix(build): remove stub scanner**
- **chore: regenerate with latest tree-sitter**

Fixes #9

### CODE REVIEW

**Comment by murtaza64** [comment]
Nice, sorry forgot about that stub scanner

**Comment by clason** [comment]
Didn't expect this to be a problem, either, but `tree-sitter build` is surprisingly eager...

**Comment by murtaza64** [comment]
@clason actually why did you add prebuildify?

**Comment by clason** [comment]
I didn't; `tree-sitter` did. This is the standard boilerplate that is (now) generated.

(Another aspect where `tree-sitter` is maybe a bit too eager, in my view...)

**Pull request merged**
