### PR TITLE
Update placeholders in Cargo.toml

### PR DESCRIPTION
**Pull request by varungandhi-src**

### CODE REVIEW

**Comment by murtaza64** [comment]
hey, thanks for the PR. did you test the rust bindings? I don't use them so hadn't noticed these were out of date

**Comment by varungandhi-src** [comment]
> did you test the rust bindings?

I did run `cargo test` and that passed successfully. Is that what you mean?

> I don't use them so hadn't noticed these were out of date

Curious how you're using it. Just the generated C code from Lua/NeoVim?

**Comment by murtaza64** [comment]
Yup, I just install the parser in neovim. I assume it just compiles the C code, and that the rust bindings and stuff are for if you want to use the treesitter parser in a rust program? (looks like the rust lib is also just a wrapper for the C)

**Comment by varungandhi-src** [comment]
> the rust bindings and stuff are for if you want to use the treesitter parser in a rust program?

Yes

**Comment by LetsMelon** [comment]
Please try to merge this PR. Without the changes applied, I wasn't able to build the crate.

**Comment by murtaza64** [comment]
Could you fix the merge conflicts please? I'm not familiar with the rust bindings

**Comment by LetsMelon** [comment]
I would but I can't see them, GitHub just shows me the warning that

```
This branch has conflicts that must be resolved
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.
```

**Comment by murtaza64** [comment]
As of https://github.com/murtaza64/tree-sitter-groovy/commit/f3615006429251a966d7452bd46a0171364bcb7b there are no more references to YOUR_LANGUAGE_NAME. Not sure if anything else is needed to get bindings working, but this PR is obsolete now so closing it.

**Pull request closed without merging**
